import { ArchetypeTemplate } from './types';

// Re-export ArchetypeTemplate for convenience
export type { ArchetypeTemplate } from './types';

/**
 * Pre-defined story archetype templates
 * Each template contains the structure for a complete story arc
 */
export const ARCHETYPES: ArchetypeTemplate[] = [
  {
    name: 'RagsToRiches',
    title: 'From Street Cat to Internet Sensation',
    narrative:
      'A chubby orange cat goes from living in a cardboard box to becoming a beloved internet celebrity',
    overallMood: 'heartwarming',
    musicStyle: 'emotional piano with uplifting crescendo, royalty-free style',
    sceneTemplates: [
      {
        description: 'Orange cat sleeping in dirty cardboard box in rainy alley',
        subtitleText: 'Day 1: Living my best box life',
        mood: 'sad',
        environment: 'dark rainy alley, trash cans, puddles',
        catAction: 'shivering and curled up in cardboard box',
        cameraMotion: 'slow dolly in, rain visible',
      },
      {
        description: 'Kind human discovers the cat and offers food',
        subtitleText: 'Wait... is that... FOOD?',
        mood: 'hopeful',
        environment: 'same alley, human kneeling with food bowl',
        catAction: 'cautiously approaching, sniffing, big curious eyes',
        cameraMotion: 'close-up on cat face, then wide shot',
      },
      {
        description: 'Cat being gently picked up and wrapped in warm blanket',
        subtitleText: 'I guess I have a human now',
        mood: 'heartwarming',
        environment: 'human arms, soft blanket, gentle lighting',
        catAction: 'looking up with grateful eyes, starting to purr',
        cameraMotion: 'intimate close-up, soft focus',
      },
      {
        description: 'First bath and grooming session',
        subtitleText: 'The betrayal! But... I do feel fresh',
        mood: 'funny',
        environment: 'bathroom sink, soap bubbles, towels',
        catAction: 'dramatic wet cat look, then fluffy and clean',
        cameraMotion: 'before/after split, slow reveal',
      },
      {
        description: 'Cat exploring cozy new home, belly wiggling',
        subtitleText: 'All this... for ME?',
        mood: 'heartwarming',
        environment: 'modern apartment, cat toys, sunny window',
        catAction: 'waddling around, belly swaying, investigating everything',
        cameraMotion: 'tracking shot following the chonk',
      },
      {
        description: 'Human taking photos of cat doing silly poses',
        subtitleText: 'Day 30: I am... the model',
        mood: 'funny',
        environment: 'living room, smartphone on tripod, ring light',
        catAction: 'striking poses, sitting in weird positions',
        cameraMotion: 'phone camera POV, multiple angles',
      },
      {
        description: 'Phone screen showing viral TikTok with millions of views',
        subtitleText: 'I\'m famous???',
        mood: 'dramatic',
        environment: 'phone screen close-up, view counter climbing',
        catAction: 'cat looking at screen with confused expression',
        cameraMotion: 'zoom into phone screen, then cut to cat reaction',
      },
      {
        description: 'Cat lounging luxuriously with treats and toys everywhere',
        subtitleText: 'Living my best life now',
        mood: 'epic',
        environment: 'cat palace setup, premium bed, multiple food bowls',
        catAction: 'sprawled out majestically, belly up, absolute chonk',
        cameraMotion: 'slow pan revealing the luxury cat life',
      },
    ],
  },
  {
    name: 'FromShelterToHome',
    title: 'The Shelter Cat Who Found Their Person',
    narrative:
      'An overlooked shelter cat finally catches the eye of someone special',
    overallMood: 'heartwarming',
    musicStyle: 'gentle acoustic guitar, emotional build, royalty-free',
    sceneTemplates: [
      {
        description: 'Fat orange cat in shelter cage looking sad',
        subtitleText: 'Day 156 at the shelter',
        mood: 'sad',
        environment: 'animal shelter, metal cage, fluorescent lighting',
        catAction: 'sitting alone, watching other cats get adopted',
        cameraMotion: 'slow push in through cage bars',
      },
      {
        description: 'Other cats getting adopted while orange cat watches',
        subtitleText: 'Everyone gets picked but me',
        mood: 'sad',
        environment: 'shelter adoption area, families with other cats',
        catAction: 'sitting in background, looking dejected',
        cameraMotion: 'focus shift from happy adoptions to lonely cat',
      },
      {
        description: 'Someone stops and makes eye contact with the orange cat',
        subtitleText: 'Wait... they see me?',
        mood: 'hopeful',
        environment: 'in front of cage, person\'s face at cat level',
        catAction: 'perking up, making eye contact, ears forward',
        cameraMotion: 'shot-reverse-shot between human and cat',
      },
      {
        description: 'Person reaches hand into cage, cat headbutts it',
        subtitleText: 'You. I choose you.',
        mood: 'heartwarming',
        environment: 'inside cage, warm lighting',
        catAction: 'enthusiastic headbutts, purring, rubbing against hand',
        cameraMotion: 'intimate close-up of interaction',
      },
      {
        description: 'Signing adoption papers, cat in carrier watching',
        subtitleText: 'Is this really happening?',
        mood: 'hopeful',
        environment: 'shelter front desk, adoption forms',
        catAction: 'peering out of carrier with big hopeful eyes',
        cameraMotion: 'alternating between paperwork and cat face',
      },
      {
        description: 'Car ride home, cat looking out window',
        subtitleText: 'Goodbye shelter. Hello... home?',
        mood: 'heartwarming',
        environment: 'car interior, windows showing city passing by',
        catAction: 'curiously watching scenery, gradually relaxing',
        cameraMotion: 'side view of cat, reflections in window',
      },
      {
        description: 'First moments in new home, cautious exploration',
        subtitleText: 'This is all mine?',
        mood: 'heartwarming',
        environment: 'cozy home, cat-proofed space, new toys',
        catAction: 'slowly exploring, sniffing everything, tail up',
        cameraMotion: 'follow cam at cat height',
      },
      {
        description: 'Cat cuddled up sleeping with new owner on couch',
        subtitleText: 'Finally found my person',
        mood: 'heartwarming',
        environment: 'living room couch, soft blanket, golden hour light',
        catAction: 'sleeping peacefully, paw on human, gentle breathing',
        cameraMotion: 'slow pullback revealing peaceful scene',
      },
    ],
  },
  {
    name: 'StreamerCatGlowUp',
    title: 'From Zoom Bomb to Gaming Legend',
    narrative:
      'A chonky orange cat accidentally becomes a streaming sensation',
    overallMood: 'funny',
    musicStyle: 'upbeat electronic, playful synth, gaming vibes',
    sceneTemplates: [
      {
        description: 'Cat walking across keyboard during important Zoom call',
        subtitleText: 'Just checking in on your meeting',
        mood: 'funny',
        environment: 'home office, computer screen, webcam view',
        catAction: 'stepping on keys, sitting on keyboard, blocking camera',
        cameraMotion: 'webcam POV, screen recording style',
      },
      {
        description: 'Screen showing Zoom reactions laughing at the cat',
        subtitleText: 'Why is everyone laughing?',
        mood: 'funny',
        environment: 'Zoom grid view, multiple people cracking up',
        catAction: 'cat sitting proudly on keyboard, oblivious',
        cameraMotion: 'screen capture with zoom reactions',
      },
      {
        description: 'Cat knocking over coffee mug onto gaming setup',
        subtitleText: 'Oops. My bad.',
        mood: 'dramatic',
        environment: 'gaming desk, RGB lights, multiple monitors',
        catAction: 'tail swishing, accidentally knocking mug',
        cameraMotion: 'slow motion capture of the chaos',
      },
      {
        description: 'Owner sets up cat bed next to gaming chair',
        subtitleText: 'Fine. You can stay.',
        mood: 'heartwarming',
        environment: 'gaming setup with new cat bed addition',
        catAction: 'testing the new bed, kneading, getting comfortable',
        cameraMotion: 'side angle of setup, cat settling in',
      },
      {
        description: 'Cat appearing on stream, chat going wild',
        subtitleText: 'THE CAT IS BACK',
        mood: 'epic',
        environment: 'gaming stream, chat overlay exploding',
        catAction: 'jumping onto desk, staring at camera majestically',
        cameraMotion: 'stream layout with chat reactions',
      },
      {
        description: 'Cat has own mini gaming chair and setup',
        subtitleText: 'I\'m a gamer now',
        mood: 'funny',
        environment: 'custom mini gaming station for cat',
        catAction: 'sitting in tiny chair, paw on tiny mouse',
        cameraMotion: 'wide shot showing both setups',
      },
      {
        description: 'Subscriber count growing rapidly with cat cam',
        subtitleText: '100K SUBSCRIBERS',
        mood: 'epic',
        environment: 'stream dashboard, analytics showing growth',
        catAction: 'sleeping in mini chair, completely unaware of fame',
        cameraMotion: 'split screen of analytics and sleeping cat',
      },
      {
        description: 'Cat with tiny headset, officially part of the brand',
        subtitleText: 'Co-streamer of the year',
        mood: 'epic',
        environment: 'professional stream setup, branded elements',
        catAction: 'wearing tiny headset, looking professional',
        cameraMotion: 'hero shot, cinematic angle',
      },
    ],
  },
  {
    name: 'VillainArcButSoft',
    title: 'The Evil Mastermind (Who Just Wants Snacks)',
    narrative:
      'Orange cat plots world domination but is actually just very food motivated',
    overallMood: 'funny',
    musicStyle: 'dramatic orchestral with playful undertones, comedy style',
    sceneTemplates: [
      {
        description: 'Cat sitting in shadow, eyes glowing, plotting',
        subtitleText: 'They will all bow to me',
        mood: 'dramatic',
        environment: 'dark room, silhouette, dramatic lighting',
        catAction: 'sitting ominously, slow tail swish',
        cameraMotion: 'low angle, dramatic zoom',
      },
      {
        description: 'Cat pushing things off table while maintaining eye contact',
        subtitleText: 'Phase 1: Assert dominance',
        mood: 'funny',
        environment: 'kitchen counter, various objects',
        catAction: 'slowly pushing cup toward edge, staring at human',
        cameraMotion: 'close-up of paw, then cat face',
      },
      {
        description: 'Cat sitting in cardboard box throne',
        subtitleText: 'Every empire needs a throne',
        mood: 'funny',
        environment: 'Amazon box decorated as throne',
        catAction: 'sitting regally, judging everything',
        cameraMotion: 'low angle hero shot, dramatic',
      },
      {
        description: 'Cat attempting to open treat cabinet',
        subtitleText: 'The vault... must be breached',
        mood: 'funny',
        environment: 'kitchen, cabinet with treats visible',
        catAction: 'jumping, pawing at cabinet, determined face',
        cameraMotion: 'action sequence, multiple angles',
      },
      {
        description: 'Human catches cat mid-heist',
        subtitleText: 'You saw nothing',
        mood: 'funny',
        environment: 'kitchen, caught in the act',
        catAction: 'frozen mid-reach, guilty expression',
        cameraMotion: 'freeze frame, zoom into guilty face',
      },
      {
        description: 'Cat receiving treat from human anyway',
        subtitleText: 'My mind control is working',
        mood: 'funny',
        environment: 'kitchen floor, treat being offered',
        catAction: 'graciously accepting treat, looking smug',
        cameraMotion: 'close-up of transaction',
      },
      {
        description: 'Cat herding human toward food bowl',
        subtitleText: 'Yes... exactly as planned',
        mood: 'funny',
        environment: 'hallway to kitchen',
        catAction: 'walking between human legs, guiding them',
        cameraMotion: 'overhead shot showing the manipulation',
      },
      {
        description: 'Cat lounging after successful meal',
        subtitleText: 'World domination can wait. Nap time.',
        mood: 'funny',
        environment: 'sunny spot, food coma setting in',
        catAction: 'sprawled out, belly up, completely relaxed',
        cameraMotion: 'pullback revealing the "mastermind" sleeping',
      },
    ],
  },
  {
    name: 'ChonkToBestFriend',
    title: 'The Unlikely Friendship',
    narrative:
      'A grumpy fat orange cat reluctantly becomes best friends with new kitten',
    overallMood: 'heartwarming',
    musicStyle: 'gentle piano with playful strings, emotional journey',
    sceneTemplates: [
      {
        description: 'Orange cat living alone, ruling the house solo',
        subtitleText: 'Life is perfect. I am king.',
        mood: 'dramatic',
        environment: 'entire house, cat in various royal positions',
        catAction: 'lounging in sunbeams, complete control',
        cameraMotion: 'montage of cat ownership',
      },
      {
        description: 'Human brings home tiny kitten in carrier',
        subtitleText: 'What is THAT',
        mood: 'dramatic',
        environment: 'living room, carrier being set down',
        catAction: 'backing away, suspicious, ears back',
        cameraMotion: 'reaction shot, zoom on horrified face',
      },
      {
        description: 'Kitten trying to play, orange cat hiding',
        subtitleText: 'No. I don\'t want to be friends.',
        mood: 'funny',
        environment: 'under bed, kitten pawing, orange cat glaring',
        catAction: 'pressed against wall, growling softly',
        cameraMotion: 'low angle under furniture',
      },
      {
        description: 'Orange cat reluctantly sharing food bowl',
        subtitleText: 'Fine. But just this once.',
        mood: 'hopeful',
        environment: 'kitchen, two food bowls close together',
        catAction: 'eating but watching kitten, protective stance',
        cameraMotion: 'overhead shot of parallel eating',
      },
      {
        description: 'Kitten copying everything orange cat does',
        subtitleText: 'Stop copying me!',
        mood: 'funny',
        environment: 'various locations around house',
        catAction: 'walking, sitting, grooming - kitten mimics all',
        cameraMotion: 'split screen or quick cuts showing mimicry',
      },
      {
        description: 'Orange cat grooming kitten while pretending not to care',
        subtitleText: 'You had something on your face',
        mood: 'heartwarming',
        environment: 'couch, afternoon light',
        catAction: 'licking kitten\'s head, trying to look casual',
        cameraMotion: 'close-up of gentle grooming',
      },
      {
        description: 'Both cats playing together with toy',
        subtitleText: 'Maybe you\'re not so bad',
        mood: 'heartwarming',
        environment: 'living room, feather toy',
        catAction: 'playfully batting toy together, both engaged',
        cameraMotion: 'active tracking of play session',
      },
      {
        description: 'Cuddled up sleeping together in cat bed',
        subtitleText: 'Okay fine. You can stay.',
        mood: 'heartwarming',
        environment: 'cat bed, both curled up together',
        catAction: 'orange cat with arm around kitten, both purring',
        cameraMotion: 'slow zoom out revealing the friendship',
      },
    ],
  },
  {
    name: 'OfficeHeroJourney',
    title: 'The Office Cat Rises',
    narrative:
      'A fat orange cat goes from office mascot to saving the workday',
    overallMood: 'epic',
    musicStyle: 'heroic cinematic, building tension, triumphant finale',
    sceneTemplates: [
      {
        description: 'Orange cat being sneaked into office in backpack',
        subtitleText: 'Mission: Infiltrate the workplace',
        mood: 'funny',
        environment: 'office building entrance, backpack with cat face peeking',
        catAction: 'peeking out of bag, eyes scanning the office',
        cameraMotion: 'POV from bag, then reveal cat',
      },
      {
        description: 'Cat exploring cubicles, employees petting',
        subtitleText: 'Morale: Boosted',
        mood: 'heartwarming',
        environment: 'office cubicles, workers looking stressed',
        catAction: 'walking desk to desk, receiving pets',
        cameraMotion: 'tracking shot through office',
      },
      {
        description: 'Cat sitting in on important meeting',
        subtitleText: 'I have thoughts on Q4 projections',
        mood: 'funny',
        environment: 'conference room, PowerPoint, serious business',
        catAction: 'sitting on table, staring at screen intently',
        cameraMotion: 'wide shot of meeting with cat prominently placed',
      },
      {
        description: 'Cat walking across keyboard, accidentally fixing code bug',
        subtitleText: 'You\'re welcome',
        mood: 'epic',
        environment: 'developer desk, multiple monitors, code visible',
        catAction: 'walking across keyboard, screen changes',
        cameraMotion: 'close-up of paws, then screen showing "BUILD SUCCESS"',
      },
      {
        description: 'Boss looking stern, approaching cat area',
        subtitleText: 'Oh no. We\'re busted.',
        mood: 'dramatic',
        environment: 'office floor, boss walking with serious expression',
        catAction: 'cat looking worried, tail puffed',
        cameraMotion: 'dramatic approach, tension building',
      },
      {
        description: 'Boss picks up cat, then smiles and pets it',
        subtitleText: 'Plot twist: Boss loves cats',
        mood: 'heartwarming',
        environment: 'same office space, mood shift',
        catAction: 'being held, purring, winning over the boss',
        cameraMotion: 'close-up of boss smile, then cat looking smug',
      },
      {
        description: 'Official "Office Wellness Cat" badge being made',
        subtitleText: 'I\'m officially employed now',
        mood: 'epic',
        environment: 'HR office, laminator, official badge',
        catAction: 'sitting proudly as badge is attached to collar',
        cameraMotion: 'close-up of badge, then proud cat',
      },
      {
        description: 'Cat has own desk with nameplate and tiny computer',
        subtitleText: 'Employee of the month, obviously',
        mood: 'epic',
        environment: 'mini desk setup, nameplate "Chief Morale Officer"',
        catAction: 'sitting at desk, paw on mouse, looking professional',
        cameraMotion: 'hero shot, cinematic reveal of full setup',
      },
    ],
  },
];

/**
 * Get a random archetype template
 */
export function getRandomArchetype(): ArchetypeTemplate {
  const randomIndex = Math.floor(Math.random() * ARCHETYPES.length);
  return ARCHETYPES[randomIndex];
}

/**
 * Get archetype by name
 */
export function getArchetypeByName(name: string): ArchetypeTemplate | undefined {
  return ARCHETYPES.find((archetype) => archetype.name === name);
}
